### ISSUE TITLE
No Longer Working with PTB

### ISSUE THREAD

**Issue by tealyt** [rauenzi/BBDInstaller#25] opened 2021-02-27 04:19 UTC
It was and then there was an update and now it isnt no matter what i do

**Comment by tealyt** [comment] 2021-02-27 04:22
ok it doesnt work with any of the 3 versions of discord

**Comment by Bluetinity** [comment] 2021-02-27 11:26
yup, same

**Comment by SkReintjens** [comment] 2021-02-27 12:06
same

**Comment by Wolf-ON** [comment] 2021-02-27 18:34
Duplicate of #23

**Comment by zerebos** [comment] 2021-04-03 18:37
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer

**Closed as completed by zerebos** 2021-04-03 18:37 UTC
